---
- name: create mongodb yum repo
  copy: src=mongodb.repo.j2 dest=/etc/yum.repos.d/mongodb.repo

- name: install mongodb packages
  yum: name={{ item }} state=installed
  with_items:
    - mongodb-org
    - mongodb-org-server

- name: create data filesystem
  include: filesystem.yml lvname=mongodata lvsize={{ mongo_lvsize }} mntdir=/var/lib/mongo owner=mongod group=mongod setype=mongod_var_lib_t

- name: increase soft rlimits
  lineinfile: dest=/etc/security/limits.d/20-nproc.conf regexp="mongod[ \t]soft" line="mongod soft nproc {{ nproc_soft_limit }}"
  notify: restart mongod

- name: tuned no-thp profile (directory)
  file: dest=/etc/tuned/virtual-guest-no-thp state=directory
  when: tuned_used

- name: tuned no-thp profile (files)
  copy: src={{ item.src }} dest=/etc/tuned/virtual-guest-no-thp/{{ item.dest }} mode={{ item.mode }}
  with_items:
    - { src: 'virtual-guest-no-thp.tuned.conf', dest: 'tuned.conf', mode: '0644' }
    - { src: 'thp-no-defrag.script.sh', dest: 'script.sh', mode: '0755' }
  when: tuned_used

- name: tuned no-thp profile activate
  command: /usr/sbin/tuned-adm profile virtual-guest-no-thp
  when: tuned_used
  
- name: mongod config
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  notify:
    - restart mongod

- name: mongod service enabled and running
  service: name=mongod enabled=yes state=started

- name: allow connection to mongo via firewalld
  firewalld: zone=internal port=27017/tcp permanent=true state=enabled
  when:
    - intif is defined
    - firewalld_used is defined
  notify:
    - reload firewall
...
