---
- fail: msg="Variable mongodb.lvsize must be defined"
  when: mongodb.lvsize is not defined

- fail: msg="Dictionary key network.intif.ip is not defined, cannot listen on intip"
  when:
    - mongodb.listen == 'intip'
    - network.intif.ip is not defined

- name: create mongodb yum repo
  copy: src=mongodb.repo.j2 dest=/etc/yum.repos.d/mongodb.repo

- name: install mongodb packages
  yum: name={{ item }} state=installed
  with_items:
    - mongodb-org
    - mongodb-org-server

- name: create data filesystem
  include: filesystem.yml lvname=mongodata lvsize={{ mongodb.lvsize }} mntdir=/var/lib/mongo owner=mongod group=mongod setype=mongod_var_lib_t

- name: increase soft rlimits
  lineinfile: dest=/etc/security/limits.d/20-nproc.conf regexp="mongod[ \t]soft" line="mongod soft nproc {{ nproc_soft_limit }}"
  notify: restart mongod

- include: tuned.yml
  when: tuned_used is defined

- name: mongod config
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  notify: restart mongod

- name: prepare keyfile
  copy: src=mongod.keyfile.j2 dest=/etc/mongod.keyfile owner=mongod group=root mode=0400 force=no
  when: 
    - mongodb.auth    == 'enabled'
    - mongodb.keyfile != 'none'
  notify: restart mongod

- name: mongod service enabled and running
  service: name=mongod enabled=yes state=started

- include: is_enabled_firewalld.yml

- name: allow connection to mongo via firewalld
  firewalld: zone=internal port=27017/tcp permanent=true state=enabled
  when:
    - network.intif is defined
    - firewalld_enabled
  notify:
    - reload firewalld
...
