---

- hosts: all
  roles:
  - role: common
  - role: network
  - role: tune
  - role: security
  - role: repos

- hosts: mongodb
  roles:
    - role: mongodb

- hosts: bacula
  roles:
    - role: bacula

- hosts: nagios
  roles:
    - role: nagios
...
