---
- name: ensure firewalld is installed
  yum: name=firewalld state=installed

- name: firewalld is enabled and running
  service: name=firewalld enabled=yes state=started

- name: check if iptables service is installed
  shell: >
    /usr/bin/systemctl list-unit-files | grep iptables.service
  register: iptables_service_installed
  failed_when: iptables_service_installed.rc == 2

- name: iptables is disabled and stopped
  service: name=iptables enabled=no state=stopped
  when: iptables_service_installed.rc == 0
  ignore_errors: True

- name: remove default services from internal firewalld zone
  firewalld: service={{ item }} zone=internal permanent=true state=disabled
  with_items:
    - ipp-client
    - mdns
    - samba-client
    - dhcpv6-client
  notify:
    - restart firewalld

- name: set fact firewalld_used
  set_fact: firewalld_used=True
...
