---
- name: enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    sysctl_set: yes
  when: router == 'yes'

- name: disable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    state: present
    sysctl_set: yes
  when: router == 'no'
...
